### ISSUE TITLE
在链接末尾添加字符串

### ISSUE THREAD

**Issue by molkes** [jiacai2050/gooreplacer#102]
## 描述问题

我想重定向某页面到它的子页面，于是添加了一条规则：在链接末尾添加字符串。
我写的规则有问题。原地址匹配成功后，打开目标地址，目标地址匹配成功，再次打开目标地址，此时目标地址末尾字符串重复，地址无效了。

## 复现步骤

1. 添加规则

匹配模式：https://space.bilibili.com/(.*)
目标地址：https://space.bilibili.com/$1/video
匹配类型：通配符

2. 测试

打开：https://space.bilibili.com/630320407
打开结果：https://space.bilibili.com/630320407/video/video

## 期待的正常行为

打开：https://space.bilibili.com/630320407
打开结果：https://space.bilibili.com/630320407/video

我想匹配`https://space.bilibili.com/【字符串A】`而不匹配`https://space.bilibili.com/【字符串A】/【字符串B】`，请问规则该怎么写？因为在其他网站要匹配【字符串】，所以问【字符串】的规则，不局限于【数字】。

**Comment by jiacai2050** [comment]
用正则就好了

```
https://space.bilibili.com/(\w*?)/?$
```
