### ISSUE TITLE
移除那两条多余的margin元素属性谢谢

### ISSUE THREAD

**Issue by bAdOoWindy** [jiacai2050/gooreplacer#105]
![图片](https://user-images.githubusercontent.com/4119845/111663533-defd5080-884b-11eb-86a1-d5827fd683a4.png)

元素宽度表现为 100%+( margin(-4px) *2 )
1920 x 1080的屏幕 元素宽度是1928px
下面的滚动条很碍眼

**Comment by jiacai2050** [comment]
现在使用的 antd 的 css 样式，没看出来你上面截图哪里有问题

**Comment by bAdOoWindy** [comment]
> 
> 
> 现在使用的 antd 的 css 样式，没看出来你上面截图哪里有问题

1928px的宽度 很不正常
元素检查 是有marginLeft和marginRight 刚好8px 手动删除元素属性后正常1920px了

**Comment by jiacai2050** [comment]
> 1928px的宽度 很不正常

是哪里不正常了，没看出来，css 不是很了解。

https://github.com/jiacai2050/gooreplacer/blob/master/cljs-src/src/gooreplacer/option/core.cljs#L20

这里有设置 gutter 为 8.

**Comment by bAdOoWindy** [comment]
> 
> 
> > 1928px的宽度 很不正常
> 
> 是哪里不正常了，没看出来，css 不是很了解。
> 
> https://github.com/jiacai2050/gooreplacer/blob/master/cljs-src/src/gooreplacer/option/core.cljs#L20
> 
> 这里有设置 gutter 为 8.

你好 我编辑了1L  ：）

**Comment by jiacai2050** [comment]
看到了，下个版本我去掉吧。

**Comment by jiacai2050** [comment]
![image](https://user-images.githubusercontent.com/3848910/112708411-de6c5600-8eec-11eb-949c-4d8af4b03a3e.png)

去掉这个 gutter 按钮就靠在一起了...  还是先不改了，你可以研究下 antd 怎么布局，然后提个 PR。

**Comment by bAdOoWindy** [comment]
https://github.com/jiacai2050/gooreplacer/blob/7000b76b01c43fcd8aed6be0202ac51bd100f808/cljs-src/project.clj#L14
提问 删掉"0.3.0"会不会自动获取最新版？
我怀疑是版本问题

**Comment by jiacai2050** [comment]
> 提问 删掉"0.3.0"会不会自动获取最新版？

不会
