### ISSUE TITLE
其实呢，以前的话firefox有个类似的扩展叫Mason

### ISSUE THREAD

**Issue by daiaji** [jiacai2050/gooreplacer#108]
功能几乎一样。
但Mason的API可以被专门编写的脚本调用…
反正解压就能看源码，说起来17年那会还有人用这个扩展。
反馈BUG的论坛早就炸了。
[这个页面](https://sites.google.com/site/tiramason/js)当年应该是存Mason的脚本。
[mason-0.3.7.9-fx.tar.gz](https://github.com/jiacai2050/gooreplacer/files/7179923/mason-0.3.7.9-fx.tar.gz)
下个大版本搞成这样如何？
不过兼容Mason的语法可能就没价值了。
大部分脚本已经失效了，但可作为研究的样本。
当初还挺多脚本做了从油猴到Mason的移植，主要是油猴的延迟生效很烦，用Mason脚本效果好很多。
包括油猴处理CSS那部分，简直是说不出话来。
油猴处理Headers就是永远的痛了。
WebExtensions的完善度应该能支撑这个体量的扩展吧。

**Comment by jiacai2050** [comment]
你好，没看到有什么具体的建议，mason 也没了解过。
感觉 gooreplacer 已经稳定了，除了 bugfix 不会再有什么新特性了。

**Comment by daiaji** [comment]
只是止于此当然也就不需要管了，想更强的话，大可以做成主打头修改重定向的脚本引擎，新的脚本引擎确实缺少这方面的功能。
实际我们不但是失去了mason，而且还失去了UserchromeJS，类似的新扩展都没有。
开新坑也不错嘛。

**Comment by jiacai2050** [comment]
你是指类似油猴脚本那样的引擎？

我之前没想过这个，感兴趣你可以描述下大概这个引擎怎么工作？现有的 WebExtensions 是否满足需求？如果能做出个原型出来就更好了。

**Comment by daiaji** [comment]
理论上既然油猴已经跑在WebExtensions上了，那么至少跑个脚本引擎应该没问题，但油猴一直没有HTTP头修改以及URL重定向的API，似乎也不会有了吧。
“Mason扩展是一个应用于Firefox的扩展，工作原理是监视和修改Http通讯协议的头信息，以实现众多功能。每个功能都由”规则”来实现，不同规则实现不同功能。扩展本身已经自动安装了若干规则以方便使用，并允许各规则单独禁用/可用的设定。支持类GM脚本是这个扩展最大的亮点。”
Mason的生态位和油猴并不是冲突的。
似乎是WebExtensions当初完成度过低，mason的移植计划就一直在搁置，久而久之这个生态位就一直属于空缺状态了。
现在的WebExtensions完成度，应该能够构建那样的脚本引擎了，至少gooreplacer已经能够修改HTTP头与实时重定向URL了。
然后Mason 0.3.7.9大概能跑在Firefox 53上。
