### ISSUE TITLE
建议将配置页面的静态资源文件与插件一同打包 而非使用 jsDelivr

### ISSUE THREAD

**Issue by Lehmaning** [jiacai2050/gooreplacer#110]
jsDelivr 有的时候并不稳定，而且某些情况下会导致脚本无法离线使用，比如前段时间 jsDelivr 切换国内节点，一段时间无法访问，导致 Gooreplacer 配置界面出错，无法编辑规则。

**Comment by jiacai2050** [comment]
欢迎提个 PR 来修改。
