### ISSUE TITLE
开启在线规则会影响perfetto ui（https://ui.perfetto.dev/）的使用

### ISSUE THREAD

**Issue by jianzhoujz** [jiacai2050/gooreplacer#113]
开启在线规则会影响[perfetto ui](https://ui.perfetto.dev/)的使用，是不是规则有点问题

报错：`Refused to connect to 'https://storage-googleapis.lug.ustc.edu.cn/perfetto-misc/example_android_trace_15s' because it violates the following Content Security Policy directive: "connect-src 'self'`

![image](https://user-images.githubusercontent.com/35226412/150074079-3bc2aad5-fef7-40dd-ad76-a7d55ef625de.png)

**Comment by jiacai2050** [comment]
Content Security Policy 是安全规则，不允许加载除 self 之外的资源，可参考下面链接解决；
https://github.com/jiacai2050/gooreplacer/issues/13
