### ISSUE TITLE
中科大的代理已经无了

### ISSUE THREAD

**Issue by Lemonawa** [jiacai2050/gooreplacer#115]
这个还可以用https://u.sb/css-cdn/

**Comment by jiacai2050** [comment]
@Lemonawa 如果你还在用，看看把 https://github.com/jiacai2050/gooreplacer/blob/master/gooreplacer.gson 里的规则替换下吧。

**Comment by Lemonawa** [comment]
> @Lemonawa 如果你还在用，看看把 https://github.com/jiacai2050/gooreplacer/blob/master/gooreplacer.gson 里的规则替换下吧。

好嘞
