### ISSUE TITLE
配置完成后隔一段时间失效

### ISSUE THREAD

**Issue by AdminHcat** [jiacai2050/gooreplacer#117]
Google Chrome：版本 99.0.4840.0（正式版本）dev （64 位）
System：Windows 10 专业工作站版  21H1
插件版本：3.12.1  Google 扩展商店下载

重定向规则配置好后隔几天就消失了  期间未修改过插件任何相关配置，且插件一直处于开启状态

**Comment by jiacai2050** [comment]
规则是记录在 localStorage 里面的，确认两点：

1. 是不是隐私模式？
2. 是不是有其他插件会去清理？

**Comment by jiacai2050** [comment]
没有更多线索就先关闭了，有疑问可以再打开

**Comment by AdminHcat** [comment]
使用的开发版chrome ，似乎每次更新浏览器 ，规则都会被删除
