### ISSUE TITLE
firefox91修改header无效？

### ISSUE THREAD

**Issue by w22gb8** [jiacai2050/gooreplacer#118]
是我姿势不对？
```
{
  "createBy": "http://liujiacai.net/gooreplacer/",
  "version": "3.11.2",
  "createAt": "2022/3/10 下午4:03:30",
  "redirect-rules": [],
  "cancel-rules": [],
  "request-headers": [
    {
      "src": "*google.com*",
      "kind": "wildcard",
      "op": "modify",
      "name": "User-Agent",
      "value": "test",
      "enable": true
    },
    {
      "src": ".*google\\.com.*",
      "kind": "regexp",
      "op": "modify",
      "name": "User-Agent",
      "value": "test",
      "enable": true
    }
  ],
  "response-headers": []
}
```

**Comment by jiacai2050** [comment]
你是怎么确认无效的？可以用下面这个服务测试下：
- http://httpbin.org/headers

**Comment by jiacai2050** [comment]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/3848910/157634603-9bab2e77-a8ee-4fa7-a0d6-0a819c5d416f.png">

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/3848910/157634648-74e5f6e2-9a4e-4986-8a12-2d8fb93ae7da.png">
测试了下是可以的

**Comment by w22gb8** [comment]
很奇怪，我测试还是不行。
![2022-03-10_174433](https://user-images.githubusercontent.com/1817391/157635448-9b84826d-7294-48e5-b1af-186d29bcf300.jpg)
![2022-03-10_174444](https://user-images.githubusercontent.com/1817391/157635449-921ea59d-a74b-4c31-b2fc-d941fe799b3b.jpg)

**Comment by jiacai2050** [comment]
浏览器修改头信息比较谨慎，不能随便乱加 header
- https://developer.chrome.com/docs/extensions/reference/webRequest/#life-cycle-of-requests
