### ISSUE TITLE
cdn.jsdelivr.com挂掉了，扩展无法使用

### ISSUE THREAD

**Issue by Leon406** [jiacai2050/gooreplacer#123]
可以改成 https://fastly.jsdelivr.net

https://github.com/jsdelivr/jsdelivr/issues/18397

**Comment by jiacai2050** [comment]
我周末抽空弄下，改成本地吧，靠谱些

**Comment by Leon406** [comment]
已经临时手动替换成本地文件
然后配置cdn.jsdelivr.net 重定向fastly.jsdelivr.net

**Comment by jiacai2050** [comment]
3.13.0 已经发布解决了，edge/chrome/firefox 应用商店也都已经更新。

**Comment by charescape** [comment]
@jiacai2050 刚搜了一下，edge应用商店没有更新，还是 2.12.1 版本，是不是还在审核啊？

**Comment by jiacai2050** [comment]
是还在审核
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/3848910/170036998-71fe08a7-308e-4dfb-9c5f-d1674a18b854.png">
Microsoft is reviewing your submission currently. Expect to hear back from us in 7 business days.
