### ISSUE TITLE
cdn.jsdelivr.net 坏了 麻烦及时换成 fastly.jsdelivr.net

### ISSUE THREAD

**Issue by ersrohu** [jiacai2050/gooreplacer#124]
今天中午我打开这个的扩展，然后本来想调点东西，结果你猜怎么着，打不开了。 
![image](https://user-images.githubusercontent.com/102342661/169040123-47ba6530-f6e7-4518-b680-688e5abaaff8.png)
然后我就去扒源代码，发现这里用的jsdelivr又双叒叕坏了。 
![image](https://user-images.githubusercontent.com/102342661/169040396-d7b58d9b-75c1-4a95-82cb-2810d70c3ff9.png)
上次在我的网站上也遇到过这种情况，只要把`cdn.jsdelivr.net`换成`fastly.jsdelivr.net`就可以了。并且`fastly.jsdelivr.net`相对来说比较稳定，我用了很久都没坏。 
希望作者能速速更改。

**Comment by ersrohu** [comment]
#jsdelivr/jsdelivr/issues/18397

**Comment by jiacai2050** [comment]
重复了 https://github.com/jiacai2050/gooreplacer/issues/123
