### ISSUE TITLE
请问如何将源代码做成扩展导入Chrome

### ISSUE THREAD

**Issue by GenuineNP** [jiacai2050/gooreplacer#127]
您好,因为css和js的网站被RST了,设置页面显示不出来
我因此我下载了您的最新Master分支,然后试图在浏览器中手动打包 gooreplacer-master\cljs-src\resources,以替换旧版本,但是导入失败.
完全不懂.....举步维艰 ,希望有懂的朋友们指点一下.
还有此种情况下如何导出原有的规则文件呢? 不想在安装新扩展的时候将旧配置丢弃了,但是设置页面也不能正常显示,我毫无办法.
谢谢大家!

**Comment by jiacai2050** [comment]
应用商店已经更新，直接下载有困难嘛

**Comment by jiacai2050** [comment]
我把 zip 包也打好了，直接解压安装就好了
- https://github.com/jiacai2050/gooreplacer#zip-%E5%8C%85
- - https://github.com/jiacai2050/gooreplacer/releases/tag/v3.13.0

**Comment by GenuineNP** [comment]
> 应用商店已经更新，直接下载有困难嘛

是的,没有工具....... :( 打不开chrome的应用商店

**Comment by GenuineNP** [comment]
> 我把 zip 包也打好了，直接解压安装就好了
> 
> * https://github.com/jiacai2050/gooreplacer#zip-%E5%8C%85
> * * https://github.com/jiacai2050/gooreplacer/releases/tag/v3.13.0

感谢您的奉献! 祝您晚上愉快!

**Comment by GenuineNP** [comment]
> 应用商店已经更新，直接下载有困难嘛

还有个问题,就是导入后会提醒:Manifest version 2 is deprecated, and support will be removed in 2023",看来是menifest的版本落后了? 而且2023年chrome就不资瓷了,您能看一下这个吗?

**Comment by jiacai2050** [comment]
已知问题，到时候只是不能更新，使用没有问题。
#128
