### ISSUE TITLE
移除 jsDelivr 源

### ISSUE THREAD

**Issue by kobe-koto** [jiacai2050/gooreplacer#129]
您好，您發行的插件使用了 jsDelivr CDN 。 由於其在中國大陸的ICP備案被吊銷 ， 大部分地區無法訪問其 CDN 服務。導致貴外挂程式在中國大陸的使用產生了困難。

## 所以請更換 CDN ， 不要再使用 jsDelivr 。

**Comment by jiacai2050** [comment]
Duplicated #123
