### ISSUE TITLE
Online Rule Update Issue

### ISSUE THREAD

**Issue by XiaobingziZYB** [jiacai2050/gooreplacer#143]
最近经常会遇到这个报错... 
请问有什么解决办法吗？
![image](https://github.com/jiacai2050/gooreplacer/assets/59931223/c72a5c95-52cc-447a-85fb-4cd2532ff7ce)

**Comment by jiacai2050** [comment]
https://raw.githubusercontent.com/jiacai2050/gooreplacer/master/gooreplacer.json

地址换了，最后是 json
