### ISSUE TITLE
Firefox 2.0 还没提交到 amo？

### ISSUE THREAD

**Issue by ivysrono** [jiacai2050/gooreplacer#26]
我还想知道，2.0 后 android 版提交到 amo 还会提示错误么？

**Comment by jiacai2050** [comment]
现实是，Firefox 2.0 也还没通过 AMO 审核，有些权限问题，我还在和他们沟通

**Comment by ivysrono** [comment]
真心希望能解决 android 版的问题，目前在 android 上没有好用的重定向扩展啊，除非我去自定义 httpseverywhere。

**Comment by jiacai2050** [comment]
好的，这个周末我再找找原因。解决了会在这个 issue 上通知你。
