### ISSUE TITLE
chrome 浏览器插件中需要的谷歌字体无法从镜像下载

### ISSUE THREAD

**Issue by shenhf** [jiacai2050/gooreplacer#31]
最近使用google的office在线编辑插件，发现很慢，原来卡在字体上了：
https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic
从网上找到了 gooreplacer 插件，从浏览器地址栏打开上面链接，自动转换很快：
https://fonts.proxy.ustclug.org/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic
但是很遗憾office在线编辑插件中需要获取字体时无法转换。

**Comment by jiacai2050** [comment]
网址多少

**Comment by shenhf** [comment]
https://chrome.google.com/webstore/detail/office-editing-for-docs-s/gbkeegbaiigmenfmjfclcdgdpimamgkj

**Comment by shenhf** [comment]
还有一个问题，我想把所有 http://abc.com/* 的request转换为 https://abc.com/*，规则应该怎么写？原始URL填写 http://abc.com 目的URL填写https://abc.com貌似不行。
浏览器报错：
Mixed Content: The page at 'https://wf.********' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://wf.**********'. This request has been blocked; the content must be served over HTTPS.
我希望通过gooreplacer 转换为https 。可能是无法获取 ajax request 的原因吧

**Comment by jiacai2050** [comment]
![image](https://cloud.githubusercontent.com/assets/3848910/23507469/3e40648e-ff88-11e6-878b-5afc9304a4e1.png)

我上面的规则是可以的，ajax 的请求应该也没问题，你的 ajax 请求地址是多少
