### ISSUE TITLE
可以重定向到本地吗？

### ISSUE THREAD

**Issue by bytesloop** [jiacai2050/gooreplacer#32]
类似于local cdn，先下注好资源到本地电脑，然后再重定向，这样速度更快？请问本地规则要怎么样自定义？

**Comment by GalvinGao** [comment]
默认浏览器在使用`http`, `https`等协议时不能使用`file`协议（意即本地文件）。除非在本地开个**文件服务器**然后填入**服务器地址**。这样做的缺点就是有些配置过_origin_的网站可能无法**正常获取资源** 使用的时候注意一点就行

**Comment by jiacai2050** [comment]
看了下 https://developer.chrome.com/extensions/webRequest 
貌似是可以重定向到本地的，回来我试试。

**Comment by jiacai2050** [comment]
- https://stackoverflow.com/questions/13380015/redirecting-a-url-to-a-local-file-using-the-webrequest-api-for-chrome-extensions

这里有说明，必须把本地文件放到扩展内部一起打包。所以目前还是推荐自己托管这些资源。
国内的话，可以试试
- https://coding.net/
- https://gitee.com/

**Comment by KnIfER** [comment]
可以自己开个本地服务啊，比如Java的nanohttpd之类的

**Comment by KnIfER** [comment]
https://www.bilibili.com/video/BV1PJ411j752?from=search&seid=10436792841071595855&spm_id_from=333.337.0.0

**Comment by jiacai2050** [comment]
一行 python 就行了：
```
python3 -m http.server --bind 127.0.0.1
```
