### ISSUE TITLE
gravatar.proxy.ustclug.org现在不能访问？

### ISSUE THREAD

**Issue by meteormatt** [jiacai2050/gooreplacer#35]
<img width="901" alt="dingtalk20170901162634" src="https://user-images.githubusercontent.com/424475/29961470-58742ffe-8f32-11e7-9abe-0c8c4d405819.png">

**Comment by jiacai2050** [comment]
可能是科大网络不稳定。

**Comment by meteormatt** [comment]
不稳定了2个月吗？。。。。

**Comment by jiacai2050** [comment]
这么久了呀，要不你发个 pr 把那些失效的规则去掉吧，多谢了。
