### ISSUE TITLE
在firefox 57下不能使用了

### ISSUE THREAD

**Issue by XindongSu** [jiacai2050/gooreplacer#36]
这个插件的确很好用！但 legacy 插件在 firefox 57 下面被全部停用，用不到了。

**Comment by jiacai2050** [comment]
https://github.com/jiacai2050/gooreplacer4chrome#warn

**Comment by jiacai2050** [comment]
重新打包提交

**Comment by jiacai2050** [comment]
已经重新提交，已经通过审查，可直接下载：
https://addons.mozilla.org/zh-CN/firefox/addon/gooreplacer/
