### ISSUE TITLE
调研其他同类扩展

### ISSUE THREAD

**Issue by jiacai2050** [jiacai2050/gooreplacer#40]
- https://www.requestly.in/rules/  功能最丰富，有 header 改写，URL cancel 功能
- https://chrome.google.com/webstore/detail/link-redirect-trace/nnpljppamoaalgkieeciijbcccohlpoh 主要是在 popup 页面展现当前页面的 cookie header
- http://einaregilsson.com/writing-a-browser-extension-for-three-browsers/

**Comment by gggccc44** [comment]
火狐的1.2.1不能重定向url地址栏，我就又用了个REDIRECTOR专门做这事，更习惯gooreplacer因为简单。昨天突然谷歌浏览器就升级了gooreplacer 2.0，规则也没了，ui也全英文很不爽，幸好那几个字还算认识，以前也备份了规则，导进去好像正常，
火狐就暂时不升级了，反正目前功能够用懒得搞了

Redirector设置要几步觉得麻烦没怎么用，谷歌Redirector貌似还有个国人修改版，Requestly没用过，因为用重定向关键字搜就没看到过，所以说名字很重要，装来看了下功能确实强大但是我挺懵，正则都不会写呢。。。

link-redirect-trace也装来看了下挺好的工具，用来配合gooreplacer应该不错

**Comment by jiacai2050** [comment]
你好，感谢反馈。
关于规则迁移，可以参考：https://github.com/jiacai2050/gooreplacer4chrome/blob/master/doc/guides.md#%E8%BF%81%E7%A7%BB%E6%8C%87%E5%8D%97v10--v20
新版 点击 Help 按钮也可以看到。这个更改我也是再三犹豫，但是考虑到性能与要增加新的功能，就废弃了之前的规则，但是导入还是没问题的。

之前 Firefox 那边更新确实很滞后，主要是他们审查比谷歌的严，一次三番审核不通过就没继续了。
现在 Firefox 的 WebExtensions 兼容性更好了，Chrome 的代码稍加修改就能跑在 Firefox 上，如果你有需要可以再看看：
https://addons.mozilla.org/zh-CN/firefox/addon/gooreplacer/

关于语言，目前我还是想把精力 focus 在功能与国际化上，你也看到新版去掉了一些用处不大但占用性能的功能（比如：定时更新），后面会把这一点补充上。

以后有哪里用的不爽欢迎再来吐槽，谢谢。

**Comment by gggccc44** [comment]
我只是吐槽下而已，扩展配置页面可以给句提示，其实从新配置也简单（话说用这个扩展就是因为相对其他的简单点），只是麻烦点而已

保留了迁移其实在我看来是很厉害的了，可能更新后很多懵逼了都是因为规则没了，而且要进设置页才会发现。。。把迁移说明放前面吧，弄醒目点最好。功能确实强了，不过我一般也就用转址

**Comment by KnIfER** [comment]
好难，requestly 还是收费的。
如果flutter桌面有安卓那样的webview就好了，分分钟做到资源拦截替换。

**Comment by qupig** [comment]
https://chrome.google.com/webstore/detail/decentraleyes/ldpochfccmkkmhdbclfhpagapcfdljkj

static资源重定向到本地，加速和保护隐私，但无法自定义规则，完全靠作者更新，对国内基本没做适配

能做个替代，包含一些基础功能，外加能灵活自定义的。

**Comment by WWW800** [comment]
现在这个插件是不是已经不能用呢

**Comment by jiacai2050** [comment]
> 现在这个插件是不是已经不能用呢

有问题可以新开个 issue，一直在维护的
