### ISSUE TITLE
conflict with https everywhere 

### ISSUE THREAD

**Issue by deeporist** [jiacai2050/gooreplacer#41]
Warning:
This extension failed to redirect a network request to https://apis.google.com/js/plusone.js because another extension (gooreplacer) redirected it to http://cdn.rawgit.com/jiacai2050/gooreplacer/gh-pages/proxy/plusone.js.
另外想请教一下怎么redirect到file///H:/xxxx.js这样的本机文件上去.或者怎么在自己的github上建立cdn.rawgit.com/jiacai2050/gooreplacer/gh-pages/proxy/widgets.js这种缓存再自己redirect上去(我想试试自己缓存connect.facebook.net/en_US/sdk.js)

**Comment by jiacai2050** [comment]
It doesn't matter, it's just a warning.

According to [Google doc](https://developer.chrome.com/extensions/webRequest) 
> If more than one extension attempts to modify the request, the most recently installed extension wins and all others are ignored.

**Comment by jiacai2050** [comment]
DUPLICATE: https://github.com/jiacai2050/gooreplacer4chrome/issues/5

**Comment by jiacai2050** [comment]
目前不能重定向到 file，可参考
- https://github.com/jiacai2050/gooreplacer4chrome/issues/32
