### ISSUE TITLE
custom rule dont work

### ISSUE THREAD

**Issue by deeporist** [jiacai2050/gooreplacer#42]
Redirect URL

source: 
http://\*.nga.cn/
Destination:
https://\*.nga.cn/
kind:
wildcard

win8.1 x64 
chrome ver.52
但是打开https://bbs.nga.cn后 控制台还是显示mixed content
".....was loaded over HTTPS, but requested an insecure image 'http://img4.nga.cn/......"

**Comment by jiacai2050** [comment]
Try this：
```
{:src "http://(.*).nga.cn/(.*)"
 :dst "https://$1.nga.cn/$2"
 :kind "regexp"
 :enable true}
```
Test URL:
- http://img.nga.cn/attachments/mon_201711/01/c8Q2h-kyi6KmToS7i-3m.jpg
