### ISSUE TITLE
Could redirect works under the brower's MCB?

### ISSUE THREAD

**Issue by deeporist** [jiacai2050/gooreplacer#45]
windows 8.1 x64
chrome 62.0.3202.75 (JavaScript V8 6.2.414.36)
gooreplacer 2.0
HTTPS Everywhere 2017.10.30

[https://www.eff.org/https-everywhere/rulesets](url)
> Mixed Content Blocking (MCB)
Some rulesets may trigger active mixed content (i.e. scripts loaded over HTTP instead of HTTPS). This type of mixed content is blocked in both Chrome and Firefox, before HTTPS Everywhere has a chance to rewrite the URLs to an HTTPS version. This generally breaks the site. However, the Tor Browser doesn't block mixed content, in order to allow HTTPS Everywhere to try and rewrite the URLs to an HTTPS version.

比如:
[https://bbs.a9vg.com/](url)
会因为MCB导致css等资源全被block, 尽管这些资源几乎都是可以以https访问的. 那么gooreplacer有没有可能实现使得尽管资源被MCB但仍然可以进行后续的https request?

**Comment by jiacai2050** [comment]
试了下，不行。
不仅仅是 gooreplacer 没法做到，浏览器提供的接口就不支持获取这些请求，所以所有插件都没法做到。
有人在 12 年就提出这个 issue 了，但是貌似一直没解决，感兴趣可以看下：
- https://bugs.chromium.org/p/chromium/issues/detail?id=122548

可以去投一票，让 chromium 的开发者重视下这个问题。
