### ISSUE TITLE
Missing configuration on Firefox Private Browsing

### ISSUE THREAD

**Issue by eshizhan** [jiacai2050/gooreplacer#46]
- Win10 64bit
- Firefox 56.0.2 64bit
- gooreplacer 3.5

![image](https://user-images.githubusercontent.com/1289406/32473823-607674d6-c3a4-11e7-855b-039131114d9f.png)

**Comment by jiacai2050** [comment]
https://stackoverflow.com/questions/26042423/web-storage-sessionstorage-and-localstorage-in-private-browsing-mode-incognit

> In private browsing mode, Safari, iOS Safari and the Android browsers do not support setting localStorage.
