### ISSUE TITLE
after redirect  ajax.proxy.ustclug.org not cached

### ISSUE THREAD

**Issue by wxf4150** [jiacai2050/gooreplacer#47]
https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js
转向到:
https://ajax.proxy.ustclug.org/ajax/libs/jquery/1.12.4/jquery.min.js后 

每次访问重新访问国外页面.里面 "https://ajax.proxy.ustclug.org/ajax/libs/jquery/1.12.4/jquery.min.js" 都要重新访问服务器.返回状态 200.  应该是"from cache" 才对.
而其它网站没有用到gooreplacer 的静态文件都正常"from cache"

**Comment by wxf4150** [comment]
ajax.proxy.ustclug.org 返回的头错了, **首字母**要用**大写**!
你自定义的头?
cache-control:max-age=43200
content-encoding:gzip
content-type:text/javascript; charset=UTF-8
date:Tue, 07 Nov 2017 03:44:57 GMT
expires:Tue, 07 Nov 2017 15:44:57 GMT
server:nginx
status:200
timing-allow-origin:*

正确的要这样子:
Cache-Control:max-age=604800
Connection:keep-alive
Date:Tue, 07 Nov 2017 03:45:35 GMT
ETag:"597d7f86-33d"
Expires:Tue, 14 Nov 2017 03:45:35 GMT
Last-Modified:Sun, 30 Jul 2017 06:41:10 GMT

**Comment by jiacai2050** [comment]
这个源是中科大维护的，可以在 https://github.com/ustclug/mirrorrequest/issues/154 跟踪
