### ISSUE TITLE
规则条数显示错误

### ISSUE THREAD

**Issue by ElfSundae** [jiacai2050/gooreplacer#48]
- Gooreplacer v3.6
- Chrome

一个小问题：在「导入」重复配置时，左下角的总条数显示错误，删除时这个数字两个两个减。

![image](https://user-images.githubusercontent.com/526008/32508536-476cd834-c3b0-11e7-9347-eb9455494957.png)

**Comment by jiacai2050** [comment]
目前是这样子的，只是展示时显示一条，但是存储时还是存的两条。
后面可以在导入/添加规则时加个判断，之前有的话就不导入这条了。

**Comment by ElfSundae** [comment]
@jiacai2050 嗯。顺便问下在设置里能不能查看在线规则的内容？
以前我遇到过一个问题，在线规则的内容 (GitHub地址) 更新了，但是在设置里刷新后规则没生效，可能是 Chrome 缓存，然后我给规则地址后面加了点东西 `?v` 再更新后规则就生效了。

还有，希望能支持多个在线规则。比如一个通用的 redirect-rules，一个广告或统计的 cancel-rules ，一个开发用的 request-headers。在线规则列表也应该支持开关。

**Comment by jiacai2050** [comment]
后面会支持显示在线规则。

多个在线规则感觉意义不大，你完全可以把这些东西放一个文件里面，用不同的 key 来区分，可以参考：
- https://github.com/jiacai2050/gooreplacer/blob/master/example_rules.gson

这里面每条规则也是可以设置 enable 的

**Comment by ElfSundae** [comment]
嗯 能支持 显示、开关 在线规则就很棒了 👍 

我说的例子还是有一定方便性的。比如任何人可以使用国外 CDN 的 redirect.gson 这个在线规则，部分人可能会选择使用 cancel.gson 来屏蔽 Google 百度统计等，公司团队会有一个在线规则，包括开发域名的
 redirect 规则、修改请求规则等。如果在线规则整体支持开启/禁用的话，会方便很多，一键禁用/开启某在线规则文件里的所有规则。这是我现在的使用场景，也许对普通用户来说确实意义不大。

**Comment by jiacai2050** [comment]
![image](https://user-images.githubusercontent.com/3848910/32530532-9db16e8e-c479-11e7-88cd-3330931a5040.png)

这个选择可以控制是否全局关闭在线规则。
至于多个在线规则可能意义不大，先这样吧，后面有别人有类似场景再来考虑这个。

**Comment by ElfSundae** [comment]
👌

**Comment by jiacai2050** [comment]
https://github.com/jiacai2050/gooreplacer/commit/370053ee434b16f99e3016beb7e1d515f9b7e593

3.7 版本加入了 在线规则 展示

**Comment by ElfSundae** [comment]
已更新，看到了 👍
