### ISSUE TITLE
2.0版的自定义规则存放在哪？

### ISSUE THREAD

**Issue by deeporist** [jiacai2050/gooreplacer#51]
刚才chrome更新 2.0版失效 升级到3.7后, 3.7的自定义规则归零

**Comment by jiacai2050** [comment]
可以参考这里：https://github.com/jiacai2050/gooreplacer/issues/44#issuecomment-341867667

**Comment by deeporist** [comment]
@jiacai2050 
问题是我是更新chrome完，gooreplacer 2.0版直接就是 “This extension may have been corrupted.”
整一个就是灰的, 没法enable(Not from Chrome Web Store.). 我只好去商店装的3.7版.
算了 也怪我 没做好备份 大不了再从新一点一点加好了.
chrome在扩展这方面实在太不近人情了, 现在搞得只能用从商店安装的, 自己造的只能用develop模式load, 不像火狐虽然也要官方认证, 但是人家不用花钱你自己打包传上去认证一下再下载回来就能自己用了。

**Comment by jiacai2050** [comment]
好的，麻烦告知下 Chrome 升级前后的版本，我这边观察下，看看两个版本间哪里不兼容

**Comment by deeporist** [comment]
@jiacai2050 
chrome是从62.0.3202升级到63.0.3239
