### ISSUE TITLE
不能保存数据

### ISSUE THREAD

**Issue by ed29** [jiacai2050/gooreplacer#53]
操作系统是 win 10
Firefox 版本是 57.0
问题：设置好 Online Rule List, 和 cancel URL 等，重新打开 Firefox 之后，又什么都没有了。

**Comment by jiacai2050** [comment]
gooreplacer 是新装的吗？ 看看 localStorage 里面
参考：https://github.com/jiacai2050/gooreplacer/issues/44#issuecomment-341867667

**Comment by ed29** [comment]
@jiacai2050  firefox 好像没有这个 local storage

**Comment by jiacai2050** [comment]
![image](https://user-images.githubusercontent.com/3848910/34086998-440eabf4-e3db-11e7-9a2e-eb930310c2e5.png)

Firefox 是一样的

**Comment by ed29** [comment]
@jiacai2050 找到原因了，是因为关闭了“历史记录”引起的，谢谢。


![default](https://user-images.githubusercontent.com/3096827/34087322-39ed99f8-e3dd-11e7-925a-f7174cc596b1.png)

**Comment by jiacai2050** [comment]
好的，找到问题就好。
