### ISSUE TITLE
规则覆盖

### ISSUE THREAD

**Issue by ElfSundae** [jiacai2050/gooreplacer#54]
不知道规则有没有应用顺序？比如在线规则有一个 a.com  本地也有一个 a.com 的重定向规则，但是两个的目标地址不一样，插件会以哪个为准？

我想把[在线规则](https://raw.githubusercontent.com/ElfSundae/tools/master/config/gooreplacer.gson)里的一个域名 `fonts.gstatic.com` 给取消（覆盖）掉，就创建了一条本地规则，让 `fonts.gstatic.com` 指向它自己，在沙盒里测试是 OK 的，但是浏览网页时还是被重定向到在线规则里定义的目标地址了。

![image](https://user-images.githubusercontent.com/526008/34201322-181bf1e8-e5af-11e7-89cd-3e5e602381d5.png)

![image](https://user-images.githubusercontent.com/526008/34201627-12b1e6ee-e5b0-11e7-9a0d-d6b8936cc923.png)

重新开关插件也不行。
版本 3.7

**Comment by jiacai2050** [comment]
匹配的顺序是这样的：
在线规则--> 本地规则。

但是在测试的时候先用了本地规则，下一版我会把这个测试流程与真正的重定向流程改为一致的。

**Comment by ElfSundae** [comment]
嗯，感谢。本地规则优先应该好一点 :)

**Comment by jiacai2050** [comment]
https://github.com/jiacai2050/gooreplacer/commit/ef7de5fc5002d810508870a6ffd766bcc6130619#diff-98175e8bc268c33a2c0b64b1b69e1d4cR13

3.8 已经发了，优先使用本地规则。
过几天浏览器应该就会自动更新。

**Comment by ElfSundae** [comment]
已测试 3.9 👍
