### ISSUE TITLE
This extension may have been corrupted

### ISSUE THREAD

**Issue by genru** [jiacai2050/gooreplacer#55]
version 3.9 downloaded from github, and installed and imported online rule successfully, everything looks find, however, Chrome disabled extension in approx. 10min with red message "This extension may have been corrupted." and refuse to re-enable extension.

Chrome Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by dy-shen** [comment]
Same issue for me.

My Chrome version: 63.0.3239.108 (Official Build) (64-bit)

**Comment by jiacai2050** [comment]
Sorry for my delay, I will look into the issue this weekend.

**Comment by jiacai2050** [comment]
https://stackoverflow.com/a/47763054/2163429

It looks like `update_url` is missing in manifest.json. 

I don't intend to support install via crx directly, it will do harm to users. If you guys can't connect to  Chrome Web Store, try [Chromium](https://www.chromium.org/), it doesn't require `update_url`.

**Comment by dy-shen** [comment]
@jiacai2050 With all due respect, why would anyone need this extension if he/she can connect to Chrome Web Store?
