### ISSUE TITLE
无法更新规则

### ISSUE THREAD

**Issue by eshizhan** [jiacai2050/gooreplacer#57]
Content Security Policy: 页面设置阻止读取位于 http://raw.githubusercontent.com/jiacai2050/gooreplacer/master/gooreplacer.gson 的一项资源("default-src moz-extension://46d3064e-f410-5049-9f7f-9f7db2d3e900")。

**Comment by jiacai2050** [comment]
https://github.com/jiacai2050/gooreplacer/issues/13

试试这个方法

**Comment by eshizhan** [comment]
试了，不行
![default](https://user-images.githubusercontent.com/1289406/35667970-8aad98c4-076a-11e8-960a-35137d7af987.png)

**Comment by jiacai2050** [comment]
需要 https 地址

**Comment by eshizhan** [comment]
不行的，两个都试了
![default](https://user-images.githubusercontent.com/1289406/35688424-1cca5b70-07ac-11e8-8ef9-fb5804d80d01.png)

**Comment by jiacai2050** [comment]
确实是有些问题，发了新的版本解决了。https://github.com/jiacai2050/gooreplacer/commit/019f02fed7d71a1168b3f4f21631b969566565f3
