### ISSUE TITLE
firefox 57 重启后配置丢失

### ISSUE THREAD

**Issue by gmg137** [jiacai2050/gooreplacer#58]
如题，每次重启浏览器之前的自定义规则和在线规则就都没有了

**Comment by jiacai2050** [comment]
是不是在隐私模式？

**Comment by gmg137** [comment]
@jiacai2050 不是，就是在正常模式下

环境是Linux

**Comment by jiacai2050** [comment]
在保存规则时，看看 console 里面是不是有什么报错

**Comment by gmg137** [comment]
导入配置后过一会出现错误提示：
源映射错误：TypeError: NetworkError when attempting to fetch resource.
源 URL：moz-extension://96808b42-5483-41fa-baaf-d86bf64eaf58/option/main.js
源映射 URL：antd-with-locales.min.js.map

**Comment by jiacai2050** [comment]
.map 文件找不到不要紧

**Comment by gmg137** [comment]
@jiacai2050 那就没报其它的错了，，，难道真的只能每次手动导入配置了-_-||

**Comment by jiacai2050** [comment]
可以参考这里，看看 localStorage 里面的数据。
https://github.com/jiacai2050/gooreplacer/issues/44#issuecomment-341867667

**Comment by gmg137** [comment]
@jiacai2050 问题找到了，是因为我把cookie 的有效期设置成退出 Firefox 时为止

**Comment by jiacai2050** [comment]
呃，这样是说每次打开 Firefox，会都用一份全新的 profile ？你是怎么设置的？
