### ISSUE TITLE
Online-rules时间显示有乱码

### ISSUE THREAD

**Issue by KPOPD5** [jiacai2050/gooreplacer#63]
<img src="http://ww1.sinaimg.cn/large/da6e5901ly1fpy6xgt2omj20jz0cpaa5.jpg"/>
如上图所示

**Comment by KPOPD5** [comment]
使用的是搜狗浏览器7.5.5.27421版

**Comment by jiacai2050** [comment]
这和浏览器用的编码有关，gooreplacer 本身是指定了 utf8 编码的
```
<meta charset="UTF-8">
```




<meta charset="UTF-8">
 




<meta charset="UTF-8">
 


<meta charset="utf-8">
 




<meta charset="utf-8">
 




<meta charset="utf-8">
 




<meta charset="utf-8">
 




<meta charset="utf-8">
