### ISSUE TITLE
请求支持Microsoft Edge

### ISSUE THREAD

**Issue by ArcticLampyrid** [jiacai2050/gooreplacer#64]
如题，参考[Porting an extension from Chrome to Microsoft Edge](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions)

**Comment by ArcticLampyrid** [comment]
基本上Microsoft Edge Extension Toolkit已经完成了所有工作
在manifest.json给background加上persistent属性就能转换了

**Comment by ArcticLampyrid** [comment]
`persistent: true`必然是可以的（Chrome默认值）
不过不知道gooreplacer能否工作在`persistent: false`以便节省资源
看代码应该只是event的监听（不过我不太了解cljs）

**Comment by ArcticLampyrid** [comment]
@jiacai2050 望能在Windows应用商店上线，Edge加载未验证扩展每次启动都会提示是否同意

**Comment by jiacai2050** [comment]
收到，我最晚这个周末转化试试看。

**Comment by jiacai2050** [comment]
> The only occasion to keep a background script persistently active is if the extension uses chrome.webRequest API to block or modify network requests. The webRequest API is incompatible with non-persistent background pages.

- https://developer.chrome.com/extensions/background_pages

`persistent: false` 看来不适合。

**Comment by jiacai2050** [comment]
- https://developer.microsoft.com/en-us/dashboard/registration/AccountInfo

![image](https://user-images.githubusercontent.com/3848910/42368404-84e118a0-8139-11e8-8200-3fa56e8a5f72.png)

MS 有些坑呀，还要收费 116¥ 😭，先不注册了，感觉用 Edge 的也没几个人。
