### ISSUE TITLE
从 RawGit 迁移到其他服务

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jiacai2050/gooreplacer#65]
[RawGit](https://rawgit.com/) 宣布停止服务，并且在首页上推荐了一个可以迁移到 jsDelivr 的链接，建议在此基础上换掉 gooreplacer.gson 里面几个 rawgit.com 的网址。

**Comment by KrasnayaPloshchad** [comment]
最近发现 [Staticaly](https://www.staticaly.com/) 也提供了这样的服务，可以试试。

**Comment by ganlvtech** [comment]
可以使用 GitHub Pages 不必使用 RawGit

https://jiacai2050.github.io/gooreplacer/proxy/widgets.js

https://liujiacai.net/gooreplacer/proxy/widgets.js

也可以使用 https://www.jsdelivr.com/rawgit

**Comment by KrasnayaPloshchad** [comment]
参考：https://github.com/fengyc/URLRedirector/commit/fb9c6c67eb7ae620dbb8743e05a28fff33643b48

**Comment by jiacai2050** [comment]
@KrasnayaPloshchad 提个 pr 吧，也改成 jsdelivr 的

**Comment by KrasnayaPloshchad** [comment]
已提交 #67
