### ISSUE TITLE
Migrate from cdn.bootcss.com to cdnjs.cloudflare.com/ajax/libs/

### ISSUE THREAD

**Issue by ganlvtech** [jiacai2050/gooreplacer#66]

**Comment by ganlvtech** [comment]
BootCDN has post a public notification.

> BootCDN 正在切换 CDN 服务商，如果此期间给您的站点带来问题，请给我们发邮件：cdn@bootcss.com
>
> 详细说明将会在迁移结束并稳定后另发文章。
>
> 谢谢各位的支持！

Now, <https://cdn.bootcss.com/antd/3.0.3/antd.min.css> is avaiable.

Issue closed.

**Comment by jiacai2050** [comment]
https://github.com/jiacai2050/gooreplacer/pull/73/files#diff-92491fad107e7af132fac80f7d543b3d 已经改用 cdn.jsdelivr.net
