### ISSUE TITLE
无法导入规则

### ISSUE THREAD

**Issue by SainoNamkho** [jiacai2050/gooreplacer#68]
提示  Parse rules error
![](https://user-images.githubusercontent.com/23036788/49429736-39418700-f7e4-11e8-80c8-238e53664d58.png)
下载下来本地导入则显示

> Uncaught SyntaxError: Unexpected string in JSON at position 435
    at JSON.parse (<anonymous>)
    at FileReader.<anonymous> (main.js:1369)
(anonymous) @ main.js:1369

**Comment by jiacai2050** [comment]
Thanks for report. fixed in https://github.com/jiacai2050/gooreplacer/commit/d3894cdaa140be04aef2038c3c93c59a2303d542
