### ISSUE TITLE
怎么阻止自动加上/

### ISSUE THREAD

**Issue by df1228** [jiacai2050/gooreplacer#71]
```
{
  "src": "g.cn",
  "dst": "google.com/ncr",
  "kind": "wildcard",
  "enable": true
}
```

想达到的效果是浏览器地址栏输入g.cn跳转到google.com/ncr, 而不是google.com/ncr/

谢谢@

**Comment by jiacai2050** [comment]
这样就可以了 `"src": "g.cn/$"`
更多规则可参考：
- https://github.com/jiacai2050/gooreplacer/blob/master/doc/guides.md

**Comment by df1228** [comment]
不行啊

dst 后面还是自动加上了/

**Comment by jiacai2050** [comment]
![image](https://img.alicdn.com/imgextra/i2/581166664/O1CN01UcIGOf1z69ruzWTk7_!!581166664.gif)

我这边测试没有问题，可以看看是不是最新版

**Comment by df1228** [comment]
从chrome web store上安装的 是不是最新的？

**Comment by jiacai2050** [comment]
是的

**Comment by df1228** [comment]
你试试这个配置`https://raw.githubusercontent.com/dfang/gooreplacer/master/gooreplacer.gson`

**Comment by jiacai2050** [comment]
`^g.cn/$`  -->  `g.cn/$`

我看你这个规则还是v1版本的规则，这个已经不推荐使用了，你可以试试 v2 的，也是在 [guides 页面](https://github.com/jiacai2050/gooreplacer/blob/master/doc/guides.md#%E5%86%85%E7%BD%AE%E8%A7%84%E5%88%99)有说明
```
{
  "createBy": "http://liujiacai.net/gooreplacer/",
  "version": "3.9",
  "createAt": "Wed Dec 19 2018 09:29:22 GMT+0800 (China Standard Time)",
  "redirect-rules": [
    {
      "src": "g.cn/$",
      "kind": "wildcard",
      "dst": "google.com/ncr",
      "enable": true
    }
  ],
  "cancel-rules": [],
  "request-headers": [],
  "response-headers": []
}
```

**Comment by df1228** [comment]
@jiacai2050 嗯 
建议你把README里的那个json换成v2规则的

**Comment by df1228** [comment]
@jiacai2050 我测试了 是跳到google.cn的
