### ISSUE TITLE
重定向时 Content Security Policy directive 报错

### ISSUE THREAD

**Issue by ch-yx** [jiacai2050/gooreplacer#72]
（我将 www.google.com/recaptcha redirect 到了 recaptcha.net/recaptcha）

Refused to load the script 'https://recaptcha.net/recaptcha/api.js?render=6Lf5NX8UAAAAABOdG8bYmMQThqOPUR1T4rrVra8H' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ http://www.youtube.com/iframe_api https://s.ytimg.com/ https://www.googletagmanager.com/gtag/ https://www.google-analytics.com/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

如果说错了什么真是丢脸

**Comment by jiacai2050** [comment]
可以参考[这里的](https://github.com/jiacai2050/gooreplacer/issues/13)解决方案

**Comment by ch-yx** [comment]
似乎不行啊。。。
现在不仅之前的信息没有消失，而且每次刷新页面就会出现这个：
Resource interpreted as Document but transferred with MIME type application/x-gzip: 
同时下载一个gz文件

**Comment by jiacai2050** [comment]
是在哪个网站遇到的？

**Comment by ch-yx** [comment]
https://hytale.com/signup

我按照说明加了这个![image_145.png](https://i.loli.net/2018/12/21/5c1c77e27ef34.png)
然后就会下载signup (n).gz文件在刷新的时候了。

**Comment by jiacai2050** [comment]
https://github.com/jiacai2050/gooreplacer/pull/73

我发了 3.10.0 版本解决这个问题，稍后可以更新尝试下。

**Comment by ch-yx** [comment]
真的很谢谢您！

//虽然我已经用蓝灯解决了这个事情

**Comment by jiacai2050** [comment]
应该的，后面如果有问题可以继续提 issue。🍺
