### ISSUE TITLE
如果只是修改header，不做重定向时，怎么让dist地址与src地址一致？

### ISSUE THREAD

**Issue by zhanglt** [jiacai2050/gooreplacer#75]
如果只是修改header，不做重定向时。src用了通配或者正则，不知道具体的地址，怎么让dist地址与src地址一致？谢谢！

**Comment by zhanglt** [comment]
说明一下，不启用Redirect Rules 时， 所有的Request Header Rules 都匹配不上

**Comment by jiacai2050** [comment]
能举例说明一下嘛？现在重定向与修改 header 是分别控制的。
