### ISSUE TITLE
可以重定向到127.0.0.1吗

### ISSUE THREAD

**Issue by bluesky-dark** [jiacai2050/gooreplacer#76]
在电脑上开了nginx反代上p站，需要重定向到127.0.0.1，测试下来发现用这个插件重定向访问速度比改hosts更快（大约3000ms），但是最近上不了改hosts可以正常访问
gooreplacer 3.10.0，chrome 72.0.3626.81，win10 1809

**Comment by jiacai2050** [comment]
可以把规则贴出来看一下

**Comment by bluesky-dark** [comment]
规则
![default](https://user-images.githubusercontent.com/40951818/52455257-39665600-2b8a-11e9-8414-d74d067dd592.PNG)
hosts
![2](https://user-images.githubusercontent.com/40951818/52455272-48e59f00-2b8a-11e9-9c68-4e5c7a8d462a.PNG)

**Comment by jiacai2050** [comment]
看规则是没问题的

**Comment by bluesky-dark** [comment]
把dns缓存清除以后再试又可以上了，不知道是什么原因

**Comment by bluesky-dark** [comment]
今天发现关了ssr就不能上了，hosts正常

**Comment by jiacai2050** [comment]
我本地测试了下，localhost 是可以重定向的，但是本地一般是不支持 https的，所以上述规则里面的 `*.wikipedia.com` 这条，会把 `https://foo.wikipedia.com/bar` 重定向到 `127.0.0.1/bar`，这明显不对，需要保证重定向的地址以 `http` 开头。

**Comment by bluesky-dark** [comment]
好的，我去改用别的方法
