### ISSUE TITLE
扩展本身引用了 “https://cdn.bootcss.com/antd/3.0.3/antd.min.css”，强烈建议一起打包

### ISSUE THREAD

**Issue by V0idk** [jiacai2050/gooreplacer#78]
像我的网络环境就无法访问这个https://cdn.bootcss.com/antd/3.0.3/antd.min.css。这跟扩展本身的原意不符

**Comment by jiacai2050** [comment]
现在已经换成了
- Request URL: https://cdn.jsdelivr.net/npm/antd@3.0.3/dist/antd.min.css

请更新到最新版

**Comment by V0idk** [comment]
@jiacai2050 我意思是整个网站bootcss.com访问不了。需要打包到源文件啊
