### ISSUE TITLE
无法启用在线规则

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jiacai2050/gooreplacer#79]
我发现选项页面里面 Online rules 里面只能查看规则，不能启用或禁用，怎么解决？
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0`

**Comment by KrasnayaPloshchad** [comment]
插件版本 3.10.0

**Comment by jiacai2050** [comment]
直接修改对应的 json 文件即可，插件里面只能查看 online  的规则有那些。
