### ISSUE TITLE
Firefox 31.3.0 ESR 无法查看和添加规则。

### ISSUE THREAD

**Issue by Red54** [jiacai2050/gooreplacer#8]
![qq20150107-1](https://cloud.githubusercontent.com/assets/2240638/5640188/6c7e7e08-965d-11e4-85d6-81b8a1fd01f8.png)

**Comment by jiacai2050** [comment]
如果你是mac系统，可尝试下面的步骤：
1. 卸载gooreplacer
2. 把
/Users/<%username%>/Library/Application Support/Firefox/Profiles/<%sessionid%>.default/jetpack/gooreplacer@liujiacai.net
这个文件夹删掉，重新安装试试

**Comment by Red54** [comment]
卸载，不重启FF，删除，问题依旧；
卸载，重启FF，删除，问题依旧。

**Comment by Red54** [comment]
说错了，应该是：
卸载，不重启FF，删除文件，安装，问题依旧；
卸载，关闭FF，删除文件，启动FF，安装，问题依旧。

**Comment by jiacai2050** [comment]
如果你现在安装了，在我上面说的文件夹下应该有个store.json文件，如果没有，重启firefox试试。
你把这个文件的内容贴出来吧

**Comment by Red54** [comment]
{"rules":{"ajax.googleapis.com":{"dstURL":"ajax.lug.ustc.edu.cn","enable":true},"fonts.googleapis.com":{"dstURL":"fonts.lug.ustc.edu.cn","enable":true},"themes.googleusercontent.com":{"dstURL":"google-themes.lug.ustc.edu.cn","enable":true},"fonts.gstatic.com":{"dstURL":"fonts-gstatic.lug.ustc.edu.cn","enable":true},"http._://platform.twitter.com/widgets.js":{"dstURL":"http://liujiacai.net/gooreplacer/proxy/widgets.js","enable":true},"http._://apis.google.com/js/api.js":{"dstURL":"http://liujiacai.net/gooreplacer/proxy/api.js","enable":true},"http.*://apis.google.com/js/plusone.js":{"dstURL":"http://liujiacai.net/gooreplacer/proxy/plusone.js","enable":true}}}

**Comment by jiacai2050** [comment]
从文件内容来看是正确的，不知道你那边什么情况，我在mac、windows下分别试用了Firefox 31.3.0 ESR，均正常

![rules](https://cloud.githubusercontent.com/assets/3848910/5675455/75147642-97f9-11e4-8b1c-950447c626e5.jpg)

![version](https://cloud.githubusercontent.com/assets/3848910/5675456/7e9d85be-97f9-11e4-9693-09b432bf9b30.jpg)

**Comment by Red54** [comment]
<!DOCTYPE html>
<html>
<head>
    <title>gooreplacer自定义规则</title>
    <link rel="shortcut icon" href="gooreplacer.ico">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

<h1>gooreplacer</h1>
<h5>想去哪儿，就去哪儿</h5>

<div class="actions">
    <button id="homepage">主页</button>
    <button id="import">导入</button>
    <button id="export">导出</button>
    <button id="help">帮助</button>

</div>

<div id="config" class="dialog">
    <h2>使用帮助</h2>
    <ol>
        <li>每条重定向规则有“开启/停用”两种状态</li>
        <li>在自定义规则时，可以使用通配符*，来进行模糊匹配</li>
        <li>在自定义规则时，不能包含 (, ), [, ], {, }, ?, \, + 这些特殊字符</li>
        <li>使用“导出”功能，可以把当前的重定向规则导出到本地</li>
        <li>使用“导入”功能，可以从本地加载重定向规则</li>
    </ol>
    <div class="button-row">
        <button id="close">关闭</button>
    </div>
</div>
<table id="rules" align="center">
    <tr>
        <th>
            原始URL
        </th>
        <th></th>    
        <th>
            目的URL
        </th>    
    </tr>

</table>

<div class="centered">
    <button id="more">更多</button>
    <button id="ok">确定</button>
</div>
<div class="line"></div>
<div class="centered">
    <h3>系统中已有以下规则</h3>
</div>
<table id="list" align="center"></table>
</body>
</html>

**Comment by Red54** [comment]
``` HTML
<!DOCTYPE html>
<html>
<head>
    <title>gooreplacer自定义规则</title>
    <link rel="shortcut icon" href="gooreplacer.ico">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

<h1>gooreplacer</h1>
<h5>想去哪儿，就去哪儿</h5>

<div class="actions">
    <button id="homepage">主页</button>
    <button id="import">导入</button>
    <button id="export">导出</button>
    <button id="help">帮助</button>

</div>

<div id="config" class="dialog">
    <h2>使用帮助</h2>
    <ol>
        <li>每条重定向规则有“开启/停用”两种状态</li>
        <li>在自定义规则时，可以使用通配符*，来进行模糊匹配</li>
        <li>在自定义规则时，不能包含 (, ), [, ], {, }, ?, \, + 这些特殊字符</li>
        <li>使用“导出”功能，可以把当前的重定向规则导出到本地</li>
        <li>使用“导入”功能，可以从本地加载重定向规则</li>
    </ol>
    <div class="button-row">
        <button id="close">关闭</button>
    </div>
</div>
<table id="rules" align="center">
    <tr>
        <th>
            原始URL
        </th>
        <th></th>    
        <th>
            目的URL
        </th>    
    </tr>

</table>

<div class="centered">
    <button id="more">更多</button>
    <button id="ok">确定</button>
</div>
<div class="line"></div>
<div class="centered">
    <h3>系统中已有以下规则</h3>
</div>
<table id="list" align="center"></table>
</body>
</html>
```

**Comment by jiacai2050** [comment]
这只是静态页面，初始化这个页面是由setting.js负责，setting.js是作为contentScript附加到这个页面上的
https://github.com/jiacai2050/gooreplacer/blob/master/lib/setting.js#L12

PS：如果你还是没法用，可以试试dev分支的v0.7，这个分支我在工具栏加上了图标，因为加图标这个API只能在[Firefox29+的版本使用](https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Adding_a_Button_to_the_Toolbar)，所以一直没发布正式版，你可以试试。

https://github.com/jiacai2050/gooreplacer/raw/dev/gooreplacer.xpi
