### ISSUE TITLE
请问如何打包成firefox插件

### ISSUE THREAD

**Issue by BillHu** [jiacai2050/gooreplacer#81]
从firefox上一直不能下载，请问我该如何自己打包

**Comment by jiacai2050** [comment]
是报什么错嘛？
自己编译的话，可以参考：https://github.com/jiacai2050/gooreplacer/blob/master/cljs-src/README.md

**Comment by BillHu** [comment]
谢谢，当时不知道为什么所有的firefox插件都装不了，也许是网络问题，现在可以装了
