### ISSUE TITLE
可以添加以下两个证书的镜像吗？

### ISSUE THREAD

**Issue by wyudong** [jiacai2050/gooreplacer#82]
起因是想在国内服务器验证 Google 登录之后的 token，不过验证 token 签名的时候要用到以下两个证书，而且证书会经常被 rotate。可以像 googlefonts 一样添加他们的镜像吗？

- https://www.googleapis.com/oauth2/v1/certs
- https://www.googleapis.com/oauth2/v3/certs

**Comment by jiacai2050** [comment]
插件只进行重定向，如需增加新的反向代理，可以去下面几个地方提 issue：
- https://github.com/ustclug/mirrorrequest
- https://bbs.huaweicloud.com/forum/thread-14229-1-1.html
