### ISSUE TITLE
翻页后数据出现重复的bug

### ISSUE THREAD

**Issue by x2009again** [jiacai2050/gooreplacer#86]
重定向页面翻页后出现重复数据

**Comment by jiacai2050** [comment]
什么版本？发个截图看看吧。

**Comment by x2009again** [comment]
> 
> 
> 什么版本？发个截图看看吧。
3个bug，一个是翻页后显示重复的问题，一个是删除的问题，一个是选中启用和禁用的问题
版本是最新版，上个版本就有这个问题，我在公司的电脑也是一样有这个bug。
![数据翻页后重复](https://user-images.githubusercontent.com/5449891/69723454-897fca80-1154-11ea-9453-d793dca48db7.gif)
![数据删除也有问题](https://user-images.githubusercontent.com/5449891/69723455-897fca80-1154-11ea-8114-9d3f4749fa9f.gif)
![重复规则的数据选中一个刷新后另一个也选中了](https://user-images.githubusercontent.com/5449891/69723456-8a186100-1154-11ea-8ef4-fcdcfd0f1fe2.gif)

**Comment by jiacai2050** [comment]
抱歉这边没复现，你可以看下 console 里面有没有报错。此外，与可以看看 localstorage 里面的内容，本地规则都保存在那里的。

![image](https://user-images.githubusercontent.com/3848910/69729755-dae28680-1161-11ea-8698-f91f92b4fb98.png)

**Comment by x2009again** [comment]
> 
> 
> 抱歉这边没复现，你可以看下 console 里面有没有报错。此外，与可以看看 localstorage 里面的内容，本地规则都保存在那里的。
> 
> ![image](https://user-images.githubusercontent.com/3848910/69729755-dae28680-1161-11ea-8698-f91f92b4fb98.png)
你用我这个数据测试把，应该和数据有关，我为了重现问题在后面追加了4条重复数据，我看了下控制台中存储的数据好像没有问题 ，所以虽然翻页时显示错了，但是直接刷新配置页面数据就正常了。其他2个bug用我这个数据也应该能重现。

[gooreplacer(1).zip](https://github.com/jiacai2050/gooreplacer/files/3897257/gooreplacer.1.zip)

**Comment by jiacai2050** [comment]
大概知道什么问题了， 是有重复的规则，现在是用 [src 字段](https://github.com/jiacai2050/gooreplacer/blob/master/cljs-src/src/option/gooreplacer/local_rules.cljs#L105)作为 primary key，这样重复了就会导致 antd 的分页组件异常

**Comment by x2009again** [comment]
我也猜到了，看样子不用获取源码看了。

**Comment by jiacai2050** [comment]
应该在添加、导入规则时判断是否有主键冲突，有的话直接报错或跳过。有兴趣实现这个吗？

**Comment by x2009again** [comment]
> 
> 
> 应该在添加、导入规则时判断是否有主键冲突，有的话直接报错或跳过。有兴趣实现这个吗？

兴趣是有，不过我是后台开发的，前端写js还行，打包什么的就没有接触过了，特别是这个源代码好像已经不是用的原生js了，用的lein什么的。而且这个处理的思路应该是主键用自增Id或者时间戳来处理，而不是可以修改的数据来做主键。我的出现重复是因为上次编辑或者新增的时候提交就自己重复了，估计编辑、新增保存的代码逻辑也有问题。

**Comment by jiacai2050** [comment]
赞，clojure 个人认为还是值得学一下的，我也是做后端的，clojurescript 是另一个实现，语法都一样，上手也快。
- https://github.com/magomimmo/modern-cljs
我当初是根据这个教程学的 cljs，感觉比较好，步骤很详细。
- https://liujiacai.net/blog/2017/11/22/create-firefox-chrome-extensions-in-clojurescript/
这是我之前写的总结，你也可以参考。

写 Lisp 最佳的是 Emacs，如果之前没经验，推荐 intellj+cursive 的组合。可参考
- https://liujiacai.net/blog/2016/12/31/dev-in-clojure/#Intellj-Cursive

建议对 clojure 掌握一定程度后再去看看 Emacs，我现在 Clojure/Go/Rust 都在 Emacs 里搞定。
- https://www.braveclojure.com/basic-emacs/

vscode  绝对也是可以的，但我没尝试过，你可以自行搜索。

有问题可以再沟通。Telegram：https://t.me/sicper

**Comment by jiacai2050** [comment]
@x2009again 还有兴趣吗？没有的话就把这个 issue 关了吧，遇到的人也不多。
