### ISSUE TITLE
请问什么原理，可以用来替换任意资源请求吗？

### ISSUE THREAD

**Issue by KnIfER** [jiacai2050/gooreplacer#87]
比如打开photopea很慢，是否可以用这个插件来加速呢？

**Comment by KnIfER** [comment]
希望添加 使用本地文件来替换资源请求 的功能。

**Comment by jiacai2050** [comment]
https://github.com/jiacai2050/gooreplacer/issues/32

**Comment by KnIfER** [comment]
现在应该不能够重定向首页，因为地址就真的变成重定向的那个地址了……
这个插件是运行在前端的吗？安卓的webview有个后端的资源拦截器，那个可以轻松实现我想要的。

**Comment by KnIfER** [comment]
可以替换首页资源而不替换首页网址吗？这什么语言实在是阅读不起来，去看看纯JS的旧版本还能用不……

**Comment by KnIfER** [comment]
[onBeforeRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest)


redirectUrl

**Comment by KnIfER** [comment]
看来是不能了。返回值只能定一个 redirectUrl ，不能传数据。倒是有一个重定向图片地址为data url的例子，不知能否通用。

**Comment by KnIfER** [comment]
可以用devtool实现：f12 -> source -> 启用overrides。f12 -> source -> 修改想要替换的文件并且保存。

这个方法之前就知道，不过无法替换成本机任意文件夹（比如源码目录）里的内容（目的是能够快速调试）。

**Comment by KnIfER** [comment]
用`mklink /H`创建硬连接即可，问题终结，哈哈我真牛逼。
