### ISSUE TITLE
建议上架新版edge应用商店

### ISSUE THREAD

**Issue by ljcbaby** [jiacai2050/gooreplacer#88]
如题

**Comment by foresee-io** [comment]
不错！新版Edge用上了Chromium内核，还可以自由访问其应用商店，上架到那对我们很有帮助。

**Comment by jiacai2050** [comment]
正在审核

![image](https://user-images.githubusercontent.com/3848910/84558929-1264f900-ad69-11ea-8161-92cb16e2b7e7.png)

- https://microsoftedge.microsoft.com/addons/detail/cidbonnpjopamnhfjdgfcmjmlmehjnej

**Comment by jiacai2050** [comment]
已经上架
- https://microsoftedge.microsoft.com/addons/detail/gooreplacer/cidbonnpjopamnhfjdgfcmjmlmehjnej
