### ISSUE TITLE
stackoverflow打不开

### ISSUE THREAD

**Issue by playgithub** [jiacai2050/gooreplacer#90]
chromium F12跟踪不了，有没有办法？

**Comment by jiacai2050** [comment]
在 console 里，看看是哪个 js/css 资源比较耗时，导致页面加载不出来的

**Comment by playgithub** [comment]
> 在 console 里，看看是哪个 js/css 资源比较耗时，导致页面加载不出来的
这个比较特别，只显示
https://www.stackoverflow.com/  (failed)  pending Other 0 B  ...
