### ISSUE TITLE
无法修改Referer

### ISSUE THREAD

**Issue by xbstory** [jiacai2050/gooreplacer#91]
![image](https://user-images.githubusercontent.com/48152166/80605523-cb939c00-8a65-11ea-8d1f-5397904c5443.png)
![image](https://user-images.githubusercontent.com/48152166/80605797-1dd4bd00-8a66-11ea-825a-3e83127d3431.png)

不过[Header Editor](https://github.com/FirefoxBar/HeaderEditor)这个插件可以成功修改Referer。

不知道是bug还是暂时没有支持这个特性。

希望gooreplacer可以加入这个特性。

**Comment by jiacai2050** [comment]
试了下 Firefox 是可以改的，Chrome 不知道为啥改不了 referer

**Comment by jiacai2050** [comment]
close for stale
