### ISSUE TITLE
怎么重定向chrome 的 inspect 页面？

### ISSUE THREAD

**Issue by KnIfER** [jiacai2050/gooreplacer#92]
国内无法用chrome://inspect/#devices 正常调试远程webview，点击inspect是空白的，无法加载。

有人说 chrome://inspect 会访问 `https://chrome-devtools-frontend.appspot.com/`。怎么重定向这个页面呢，我试着重定向后者，但是本地伺服没有反应，似乎并没有访问n那个站点。

![Screenshot (542)](https://user-images.githubusercontent.com/11593903/82522329-a6bdb080-9b5b-11ea-9118-883c3e22d24e.png)

看图片上，inspector.html 的地址是 `devtools://devtools/remote/serve_rev` 开头的，尝试重定向这个，可是好像无法重定向  `devtools://` 协议？

**Comment by KnIfER** [comment]
![Screenshot (543)](https://user-images.githubusercontent.com/11593903/82522946-770fa800-9b5d-11ea-8645-6f81abe36e01.png)

**Comment by KnIfER** [comment]
根据这个`https://chromium.googlesource.com/chromium/src.git/+/62.0.3178.1/chrome/browser/devtools/devtools_ui_bindings_unittest.cc`, 特殊网址
`devtools://devtools/remote/serve_rev/@版本代码/inspector.html`会在chrome内部翻译为`https://chrome-devtools-frontend.appspot.com/serve_rev/@版本代码/inspector.html`，比如`https://chrome-devtools-frontend.appspot.com/serve_rev/@015deec36d00c1f36b96fed01b8e913faf2b1e6c/inspector.html`，这是可以访问(fq)、并用此扩展重定向的。但是，即使成功重定向了后者，前者`devtools://...`仍然访问的原来的网站。

**Comment by jiacai2050** [comment]
- https://developer.chrome.com/extensions/webRequest

> The webRequest API only exposes requests that the extension has permission to see, given its host permissions. Moreover, only the following schemes are accessible: http://, https://, ftp://, file://, ws:// (since Chrome 58), wss:// (since Chrome 58), or chrome-extension://.
