### ISSUE TITLE
对这个网站无效吗?

### ISSUE THREAD

**Issue by joshatt** [jiacai2050/gooreplacer#93]
我已经安装GOOREPLACER, 规则就一条:  www.google.com/recaptcha 重定向到 recaptcha.net/recaptcha
chrome访问以下页面:
http://www.dg2freemaps.com/login/
试图登录, 得到:
Authentication failed.
User response is missing.
此时查看代码, 里面有一段:
```
<div class="gglcptch gglcptch_v3">
	<input type="hidden" id="g-recaptcha-response" name="g-recaptcha-response"> 
	<script src="https://www.google.com/recaptcha/api.js?render=6LesAYIUAAAAAMj2s2eUJfWEJNiAZTdeGONG5r5w"></script>
	<script>
	grecaptcha.ready(function() {
	  grecaptcha.execute('6LesAYIUAAAAAMj2s2eUJfWEJNiAZTdeGONG5r5w', {action: 'BWS_reCaptcha'}).then(function(token) {
	    document.querySelectorAll( "#g-recaptcha-response" ).forEach( elem => ( elem.value = token ) );
	  });
	});
	</script>
</div>
```
可见, 重定向并没有发生? 请教高人, 我该怎么解决这个问题?

**Comment by jiacai2050** [comment]
![image](https://user-images.githubusercontent.com/3848910/83862338-5f871080-a754-11ea-83b0-2a4b8075c51d.png)

我加了这么一个规则，是能生效的。你看看规则前后有没有空格之类的吧

**Comment by joshatt** [comment]
> ![image](https://user-images.githubusercontent.com/3848910/83862338-5f871080-a754-11ea-83b0-2a4b8075c51d.png)
> 
> 我加了这么一个规则，是能生效的。你看看规则前后有没有空格之类的吧
谢谢解答. 试了还是不行, 换个chrome也不行. 也许是我这边对recaptcha封锁了
