### ISSUE TITLE
火狐的隱私模式與插件的配置保存問題

### ISSUE THREAD

**Issue by deeporist** [jiacai2050/gooreplacer#98]
個人目前再用的火狐爲版本79，我是把火狐設置成了 退出清空cookie 和 從不記錄歷史，看了一下issue歷史發現這個問題似乎很久都沒解決。。。。。
亦或者有沒有火狐上同類的重定向插件可以推薦一下

**Comment by jiacai2050** [comment]
配置是存放在 localStorage 里面的，隐私模式下的配置不能持久化

> Data in a localStorage object created in a "private browsing" or "incognito" session is cleared when the last "private" tab is closed

- https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

> 退出清空cookie 和 從不記錄歷史

你的这种设置不是隐私模式吧？

**Comment by deeporist** [comment]
不好意思回復遲了，我看了一下, 這個設置的確不是真正的隱私模式, 
(https://support.mozilla.org/zh-CN/kb/%E9%9A%90%E7%A7%81%E6%B5%8F%E8%A7%88)    。
但是問題是一樣的，我從chromium上的Gooreplacer(3.11.0)導出的gooreplacer.json, 導入到火狐上的Gooreplacer(3.11.2)，火狐重啓后配置還是沒保存下來。。。。。

導入后的localStorage
![Untitled](https://user-images.githubusercontent.com/19790639/89751246-e1533b80-db01-11ea-8d8a-e2639ba4968b.jpg)

火狐重啓后
![Untitle2d](https://user-images.githubusercontent.com/19790639/89751311-195a7e80-db02-11ea-92b0-80de37adac00.jpg)
