### ISSUE TITLE
[bug] unnecessary slash appended at the end causes 404

### ISSUE THREAD

**Issue by mario206** [jiacai2050/gooreplacer#99]
input `"google.com/ncr"` turn out to be `"google.com/ncr/"` which cause 404

![image](https://user-images.githubusercontent.com/5844092/93008417-07f40e80-f5a7-11ea-8d5f-d4f2468092c2.png)
![image](https://user-images.githubusercontent.com/5844092/93008418-0c202c00-f5a7-11ea-99fe-ba019537e139.png)

**Comment by jiacai2050** [comment]
the ending slash is append automatically by browser, try `baidu.com/`
